[features]
seeds = false
skip-lint = false
[programs.localnet]
robo_swap_program = "23vjhFWh1dfDNzcsKZCdXt5XQdJSFipZaBncVpGrZmGw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jbc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
